# Generated by Django 4.1.7 on 2023-05-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer_Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(db_index=True, max_length=200)),
                ('composition', models.FloatField(db_index=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredDate', models.DateField(db_index=True, null=True)),
                ('price', models.FloatField(db_index=True, null=True)),
                ('supplier', models.CharField(db_index=True, max_length=200)),
                ('fertilizer_info', models.CharField(db_index=True, max_length=200)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(db_index=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fertilizer')),
            ],
        ),
    ]
