# Generated by Django 4.1.7 on 2023-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_fertilizer_detail_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_detail',
            name='supplier',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
