# Generated by Django 4.1.7 on 2023-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_composition1_fertilizer_element_composition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='element',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='element',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
