# Generated by Django 4.1.7 on 2023-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_fertilizer_element_element_fertilizer_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='composition',
            new_name='composition1',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='element',
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='composition2',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='composition3',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='element1',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='element2',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='element3',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
