# Generated by Django 4.1.7 on 2023-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fertilizer_element_composition4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_element',
            name='composition1',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='composition2',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='composition3',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='composition4',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='element1',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='element2',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='element3',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='element4',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
    ]
