# Generated by Django 4.1.7 on 2023-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_fertilizer_element_composition1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_element',
            name='composition5',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='element5',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_detail',
            name='fertilizer_info',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fertilizer_detail',
            name='price',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_detail',
            name='registeredDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_detail',
            name='supplier',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
