# Generated by Django 4.1.7 on 2023-05-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_fertilizer_element_composition5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_detail',
            old_name='price',
            new_name='price_USD',
        ),
    ]
