# Generated by Django 4.1.7 on 2023-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_price_fertilizer_detail_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_detail',
            name='fertilizer_info',
            field=models.URLField(blank=True, db_index=True),
        ),
    ]
