# Generated by Django 4.1.7 on 2023-06-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_container_fertilizer_amount_fertilizer_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='registeredDate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='Fertilizer_Product',
            new_name='Fertilizer',
        ),
    ]
