# Generated by Django 4.1.7 on 2023-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_registereddate_fertilizer_amount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='Date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='amount',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
