# Generated by Django 4.1.7 on 2023-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_fertilizer_amount_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_amount',
            name='Injection_Ratio',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_amount',
            name='UV_percent',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_amount',
            name='WaterVolume_m3',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
