# Generated by Django 4.1.7 on 2023-06-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_fertilizer_amount_injection_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='WaterVolume_m3',
            new_name='Water_Volume_m3',
        ),
    ]
