# Generated by Django 4.1.7 on 2023-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_fertilizer_amount_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='Media',
            field=models.CharField(choices=[('HYDROPONICS', 'SOIL')], max_length=255),
        ),
    ]
