# Generated by Django 4.1.7 on 2023-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_fertilizer_amount_media_fertilizer_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_detail',
            old_name='container',
            new_name='Fertilizer',
        ),
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='container',
            new_name='Fertilizer',
        ),
        migrations.RemoveField(
            model_name='fertilizer_cost',
            name='Fertilizers_Cost_USD',
        ),
        migrations.RemoveField(
            model_name='fertilizer_price',
            name='Price_USD',
        ),
        migrations.AddField(
            model_name='fertilizer_amount',
            name='Price_USD',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
