# Generated by Django 4.1.7 on 2023-06-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_fertilizer_amount_price_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='Price_USD',
            new_name='price_USD',
        ),
    ]
