# Generated by Django 4.1.7 on 2023-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_price_usd_fertilizer_amount_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='price_USD',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
