# Generated by Django 4.1.7 on 2023-06-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_fertilizer_amount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='price_USD',
            new_name='price',
        ),
    ]
