# Generated by Django 4.1.7 on 2023-06-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_price_usd_fertilizer_amount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer_amount',
            name='price',
        ),
        migrations.AddField(
            model_name='fertilizer_amount',
            name='price_Usd',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
    ]
