# Generated by Django 4.1.7 on 2023-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_fertilizer_amount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='amount',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='price_Usd',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
