# Generated by Django 4.1.7 on 2023-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_amount_fertilizer_amount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='Area_Ha',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
