# Generated by Django 4.1.7 on 2023-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_fertilizer_amount_area_ha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='Injection_Ratio',
            new_name='Tank_mix_Volume',
        ),
        migrations.RemoveField(
            model_name='fertilizer_detail',
            name='price_USD',
        ),
    ]
