# Generated by Django 4.1.7 on 2023-06-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_injection_ratio_fertilizer_amount_tank_mix_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='element1',
            new_name='Composition',
        ),
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='element2',
            new_name='Element',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='composition1',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='composition2',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='composition3',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='composition4',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='composition5',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='element3',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='element4',
        ),
        migrations.RemoveField(
            model_name='fertilizer_element',
            name='element5',
        ),
    ]
