# Generated by Django 4.1.7 on 2023-06-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_element1_fertilizer_element_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fertilizer')),
            ],
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dictionary'),
        ),
    ]
