# Generated by Django 4.1.7 on 2023-06-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_fertilizer_element_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Composition',
            field=models.FloatField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
