# Generated by Django 4.1.7 on 2023-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_fertilizer_element_composition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='Element',
            new_name='Composition_1',
        ),
        migrations.RenameField(
            model_name='fertilizer_element',
            old_name='Composition',
            new_name='Composition_2',
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Composition_3',
            field=models.FloatField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Composition_4',
            field=models.FloatField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Element_1',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Element_2',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Element_3',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer_element',
            name='Element_4',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
