# Generated by Django 4.1.7 on 2023-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_rename_element_fertilizer_element_composition_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_element',
            name='Date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Element_1',
            field=models.CharField(blank=True, choices=[('Nitrate', 'Nitrate [NO3N]'), ('Phosphorus', 'Phosphorus [P]'), ('Potassium', 'Potassium [K]'), ('Calcium', 'Cacium [Ca]'), ('Magnesium', 'Magnesium [Mg]'), ('Sulphur', 'Sulphur [S]'), ('Ammoniacal N', 'Ammoniacal N [NH4N]'), ('Iron', 'Iron [Fe]'), ('Manganese', 'Manganese [Mn]'), ('Copper', 'Copper [Cu]'), ('Boron', 'Boron [B]'), ('Zinc', 'Zinc [Zn]'), ('Molybdenum', 'Molybdenum [Mo]')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Element_2',
            field=models.CharField(blank=True, choices=[('Nitrate', 'Nitrate [NO3N]'), ('Phosphorus', 'Phosphorus [P]'), ('Potassium', 'Potassium [K]'), ('Calcium', 'Cacium [Ca]'), ('Magnesium', 'Magnesium [Mg]'), ('Sulphur', 'Sulphur [S]'), ('Ammoniacal N', 'Ammoniacal N [NH4N]'), ('Iron', 'Iron [Fe]'), ('Manganese', 'Manganese [Mn]'), ('Copper', 'Copper [Cu]'), ('Boron', 'Boron [B]'), ('Zinc', 'Zinc [Zn]'), ('Molybdenum', 'Molybdenum [Mo]')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Element_3',
            field=models.CharField(blank=True, choices=[('Nitrate', 'Nitrate [NO3N]'), ('Phosphorus', 'Phosphorus [P]'), ('Potassium', 'Potassium [K]'), ('Calcium', 'Cacium [Ca]'), ('Magnesium', 'Magnesium [Mg]'), ('Sulphur', 'Sulphur [S]'), ('Ammoniacal N', 'Ammoniacal N [NH4N]'), ('Iron', 'Iron [Fe]'), ('Manganese', 'Manganese [Mn]'), ('Copper', 'Copper [Cu]'), ('Boron', 'Boron [B]'), ('Zinc', 'Zinc [Zn]'), ('Molybdenum', 'Molybdenum [Mo]')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Element_4',
            field=models.CharField(blank=True, choices=[('Nitrate', 'Nitrate [NO3N]'), ('Phosphorus', 'Phosphorus [P]'), ('Potassium', 'Potassium [K]'), ('Calcium', 'Cacium [Ca]'), ('Magnesium', 'Magnesium [Mg]'), ('Sulphur', 'Sulphur [S]'), ('Ammoniacal N', 'Ammoniacal N [NH4N]'), ('Iron', 'Iron [Fe]'), ('Manganese', 'Manganese [Mn]'), ('Copper', 'Copper [Cu]'), ('Boron', 'Boron [B]'), ('Zinc', 'Zinc [Zn]'), ('Molybdenum', 'Molybdenum [Mo]')], db_index=True, max_length=200, null=True),
        ),
    ]
