# Generated by Django 4.1.7 on 2023-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_fertilizer_element_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='Date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
