# Generated by Django 4.1.7 on 2023-08-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_uploadedimage_alter_fertilizer_amount_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Composition_1',
            field=models.FloatField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
