# Generated by Django 4.1.7 on 2023-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_fertilizer_element_composition_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='Supplier',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer_element',
            name='Composition_4',
            field=models.FloatField(blank=True, db_index=True, default=0, max_length=200, null=True),
        ),
    ]
