# Generated by Django 4.1.7 on 2023-08-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_fertilizer_amount_uv_composition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizer_amount',
            old_name='Uv_Composition',
            new_name='Uv_PPM',
        ),
    ]
