# Generated by Django 4.1.7 on 2023-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_rename_uv_composition_fertilizer_amount_uv_ppm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer_Recycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Uv_Element', models.CharField(blank=True, choices=[('Nitrate', 'Nitrate [NO3N]'), ('Phosphorus', 'Phosphorus [P]'), ('Potassium', 'Potassium [K]'), ('Calcium', 'Cacium [Ca]'), ('Magnesium', 'Magnesium [Mg]'), ('Sulphur', 'Sulphur [S]'), ('Ammoniacal N', 'Ammoniacal N [NH4N]'), ('Iron', 'Iron [Fe]'), ('Manganese', 'Manganese [Mn]'), ('Copper', 'Copper [Cu]'), ('Boron', 'Boron [B]'), ('Zinc', 'Zinc [Zn]'), ('Molybdenum', 'Molybdenum [Mo]')], db_index=True, max_length=200, null=True)),
                ('Uv_PPM', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fertilizer_amount',
            name='Uv_Element',
        ),
        migrations.RemoveField(
            model_name='fertilizer_amount',
            name='Uv_PPM',
        ),
    ]
