# Generated by Django 4.1.7 on 2023-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_fertilizer_recycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_amount',
            name='Observation',
            field=models.TextField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
