# Generated by Django 4.1.7 on 2023-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_rename_amount_fertilizer_amount_fertilizer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer_price',
            name='Unit_Of_Measure',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Bag', 'Bag'), ('Pcs', 'Pcs'), ('Carton', 'Carton'), ('Pkt', 'Pkt'), ('Tons', 'Tons'), ('Bottles', 'Bottles'), ('Dose', 'Dose')], db_index=True, max_length=255, null=True),
        ),
    ]
