# Generated by Django 4.1.7 on 2023-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_fertilizer_price_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='Observation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
