# Generated by Django 4.1.7 on 2023-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_fertilizer_amount_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_amount',
            name='Observation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='about_Image',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
