# Generated by Django 4.1.7 on 2023-08-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_alter_fertilizer_amount_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
