# Generated by Django 4.1.7 on 2024-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_uploadedimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
