# Generated by Django 4.1.7 on 2024-03-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_remove_uploadedimage_image_uploadedimage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='about_Image',
            new_name='about_File',
        ),
    ]
