# Generated by Django 4.1.7 on 2024-03-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_alter_uploadedimage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
