from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('home/', views.home, name='home'),
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('Fertilizers/', views.Fertilizers, name='Fertilizers'),
    path('Fertilizers/<int:id>', views.Fertilizers, name='details'),
    path('testing/', views.testing, name='testing'),
    path('elements/', views.elements, name='elements'),
    path('ppm/', views.ppm, name='ppm'),
    path('template/', views.template, name='template'),
    path('index/', views.index, name='index'),
    path('Fertilizers/delete/<int:id>', views.delete, name='delete'),
    path('Fertilizers/delete_fertilizers/<int:id>', views.delete_fertilizers, name='delete_fertilizers'),
    path('elements/delete_elements/<int:id>', views.delete_elements, name='delete_elements'),
    path('fertilizer_list/delete/<int:id>', views.delete, name='delete'),
    path('Fertilizers/deleteprice/<int:id>', views.deleteprice, name='deleteprice'),
    path('Fertilizers/elements/', views.elements, name='elements'),
    path('Fertilizers/update/<int:id>', views.update, name='update'),
    path('Fertilizers/update/updaterecord/<int:id>', views.updaterecord, name='updaterecord'),
    path('about/', views.about, name='about'),
    path('anouncement/', views.anouncement, name='anouncement'),
    path('contacts/', views.contacts, name='contacts'),
    path('prices/', views.prices, name='prices'),
    path('weather/', views.weather, name='index'),
    path('Fertlizer_dealers/', views.Fertlizer_dealers, name='Fertlizer_dealers'),
    path('laboratory/', views.laboratory, name='laboratory'),
    path('research/', views.research, name='research'),
    path('fertilizer_list/', views.fertilizer_list, name='fertilizer_list'),
    path('regenerate_csrf_token/', views.regenerate_csrf_token, name='regenerate_csrf_token'),
    path('delete_multiple/', views.delete_multiple_items, name='delete_multiple_items'),
    path('delete_multiple_fertilizers/', views.delete_multiple_fertilizers, name='delete_multiple_fertilizers'),
    path('upload/', views.upload_image, name='upload_image'),
    path('list/', views.image_list, name='image_list'),
    
]